### ISSUE TITLE
datamodel: create datacite model based on zenodo

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-records#18]
# InvenioRDM data model

- [DataCite JSON Schema](https://github.com/datacite/schema/blob/master/source/json/kernel-4.3/datacite_4.3_schema.json) and [PDF version](https://schema.datacite.org/meta/kernel-4.3/doc/DataCite-MetadataKernel_v4.3.pdf).
- Translate all camel to snake case.
- Let's shorten common structures like schemeURI/valueURI -> scheme/value

## Metadata fields 
- [x] Resource Type (resourceTypeGeneral)
    - ``{'resourceTypeGeneral': ..., 'resourceType': ...}`` -> ``{'type': ..., 'subtype': ...}``
    - Cannot use the CV from DataCite.
    - We should have a mapping from internal types to DataCite types
    - Two level type: *Type* and *Subtype* (see Zenodo implementation).
- [ ] Identifiers:
    -  wait
- [ ] Creators: See https://github.com/inveniosoftware/invenio-rdm-records/issues/19
    - Use DataCite
- [x] Titles
    - ``title`` (string field)
    - ``additional_titles`` (like DataCite ``titles``)
- [ ] Publisher:
    - Use DataCite
    - (to be discussed in detail)
- [x] Publication Year:
    - Use ``publication_date`` instead. Must be a valid date. In the future we can support extended time format or similar to represent only years.
- [ ] Subjects
    - Use DataCite
    - To be investigated if we can simplify
- [ ] Contributors: See https://github.com/inveniosoftware/invenio-rdm-records/issues/19
    - Use DataCite
- [x] Dates
    - Use DataCite (and see Zenodo implementation)
    - Special dates: ``publication_date``, ``embargo_date``.
    - How to deal with Embargo Date?
    - Check Zenodo for description text
- [x] Language
    - Use DataCite
- [ ] Alternate and Related Identifiers:
    - Use DataCite
    - Issues with naming and metadata schema
    - Issue with resourceTypeGeneral
- [ ] Sizes
    - Use DataCite
    - sizes. Not present in Zenodo, followed DataCite.
       **Questions**: 
       - Shall we separate the unit (e.g. MB) from the number? This would be helpful for sorting/filtering.
       - Shall it be only one size in the file? Do we want metadata sizes too?
- [ ] Formats
    - Use DataCite
       **Questions**: 
       - Shall it be only one format in the file? Do we want metadata formats too (This does not make much sense IMHO)?
- [x] Version:
    - Use DataCite
- [x] Rights list:
    - Use DataCite
    - TO be understood if we can use it to link to a license vocabulary or we need a separate ``license`` field.
- [x] Descriptions:
    - ``description`` (string field)
    - ``additional_descriptions`` (like DataCite ``descriptions``)
    - How does it relate to Zenodo ``notes field`` (Note, abstract, descriptions).
    - GeoLocations:
    - Use Zenodo (see needs a description text)
- [ ] FundingReference:
    - Use DataCite
    - However, we need to understand like with licenses/rights how to link to a controlled vocabulary.

## Extras for all

- Add ``references`` (need to check zenodo structure if ok). Not all has related identifiers, sometimes is just a reference to the text.
- ``internal notes`` (discuss with ILS what they have). "curators notes", non-public notes.
- Access right. ~~Discuss ``_access``~~ TBD in the future.
- Access condition

## How to hanlde custom fields?
- See Zenodo implementation (``custom``)

## Zenodo custom fields

- Imprint
- Journal
- Part of?
- Thesis

## TODO

- Check against ILS schema.

## Discussion points for community:

- Keywords or only subjects?

\*CV: Control Vocabulary

**Comment by fenekku** [comment]
Can we merge this issue with #1 and then have one sub-issue per metadata field? This way we can keep track of our progress on each field and know when a field has been **completely** dealt with.

**Comment by fenekku** [comment]
Merging this with #1
